version="0.0.0"
replace_path="history/countries"
replace_path="history/states"
replace_path="history/units"
replace_path="map/strategicregions"
replace_path="map/supplyareas"
replace_path="common/characters"
replace_path="common/generation"
replace_path="history/general"
replace_path="events"
replace_path="common/national_focus"
replace_path="common/bookmarks"
replace_path="common/decisions"
replace_path="map"
tags={
	"Alternative History"
}
name="Russian Experiment's Field"
supported_version="1.10.8"
path="C:/Users/Grenada/Documents/Paradox Interactive/Hearts of Iron IV/mod/Russian Experiment's Field"